### ISSUE TITLE
Would you consider to publish this package to General?

### ISSUE THREAD

**Issue by singularitti** [tkf/Kaleido.jl#1]
Hi @tkf, currently I need to add this package explicitly whenever a package is dependent on it, because that it is not published on General. Would you consider publishing it? For example, I am developing one of my packages, which depends on `Kaleido.jl`. But I need to add `Kaleido.jl` to my global `Project.toml`.

**Comment by tkf** [comment]
@JuliaRegistrator `register()`

**Comment by tkf** [comment]
Sure, why not :)

**Comment by tkf** [comment]
It's registered now.
